### ISSUE TITLE
Error throw when data is using {t, y} format

### ISSUE THREAD

**Issue by cooljeffro** [3dcl/chartjs-plugin-responsive-downsample#3]
Ran into this issue with chartjs-plugin-downsample as well.

When using time series data, Chartjs allows to use 't' instead of 'x' for each data point, but an error is thrown when using this plugin with 't'.

Not a huge problem, just have to switch to 'x', but should be allowed as per the Chartjs docs:
https://www.chartjs.org/docs/latest/axes/cartesian/time.html

Great plugin, btw.

**Comment by MPursche** [comment]
Hello,

Thanks for reporting the issue. I wasn't aware that the chart data could also be defined with the `t` property. I will look into it. Should be a relatively easy fix.

Greetings
Marcel

**Comment by MPursche** [comment]
I published a new version of the plugin(1.1.2) that should work with `t` properties in the data points.

**Comment by cooljeffro** [comment]
Looks good, thanks!
