### ISSUE TITLE
Reference to NPM in README.md

### ISSUE THREAD

**Issue by Tilogorn** [3dcl/chartjs-plugin-responsive-downsample#5]
I am very happy that you took care of the old `chartjs-plugin-downsample` plugin. 

A hint in the README that you added it to `npm` would be nice, as the first hints on search engines (depending of the search term of course) point to github instead of `npmjs.org`.

Suggestion for `README.md` (in front of `configuration`):

    ### Installation

    ```bash
    $ npm install chartjs-plugin-responsive-downsample
    ```
Preview:

### Installation

```shell
$ npm install chartjs-plugin-responsive-downsample
```

**Comment by MPursche** [comment]
Hi!

Thanks for the suggestion. I added a line to the readme file.

Greetings
Marcel
