### ISSUE TITLE
Including Plugin as a JS-File

### ISSUE THREAD

**Issue by Karlito88** [3dcl/chartjs-plugin-responsive-downsample#6]
Can you create a *.min.js file to easy include the plugin without npm? Got a simple project for testing ChartJS and the Plugins for it. And don't know if using NPM is the right for the project.  

Hope you understand my issue.

**Comment by MPursche** [comment]
Hi,

The project includes a bundled file that can be directly included in the browser `dist/chartjs-plugin-responsive-downsample.bundle.min.js`. You can just download this file from github and include it in your HTML:
```html
<head>
    <title>Responsive Downsampling</title>
    <!-- Include chart.js and moment before the plugin -->
    <script src="../node_modules/chart.js/dist/Chart.bundle.js"></script>
    <script src="../node_modules/moment/min/moment-with-locales.min.js"></script>
    <script src="../dist/chartjs-plugin-responsive-downsample.bundle.min.js"></script>
</head>
```
You can have a look at the example in the repository to see how the plugin is used without `npm`.

Greetings
Marcel

**Comment by Karlito88** [comment]
Thanks
