### ISSUE TITLE
how refresh downsample

### ISSUE THREAD

**Issue by poli44** [3dcl/chartjs-plugin-responsive-downsample#8]
hi,
After 5 seconds, I add a new sample to the chart. Currently, the chart is refreshed only by zoom/pan the chart. Is there a command refreshing the algorithm?

**Comment by poli44** [comment]
var optionse = window.myLine.options.responsiveDownsample;
                    optionse.enabled = false;
                    optionse.needsUpdate = true;
                    window.myLine.update();

This is the correct answer.

**Comment by jklimke** [comment]
sorry for not answering. The complete set of options was documented in the typescript definitions of the plugin. I added the missing options to the README
